import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import "./_supressLogs";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "LinkIndex",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<header className="p-4 bg-slate-50  border ">
					<h1>LinkIndex</h1>
				</header>
				{children}
				<footer className="p-4 bg-slate-50 border">dd</footer>
			</body>
		</html>
	);
}
